# Generated by Django 4.2 on 2023-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGoszakupki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('deadline', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DataIcetrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('deadline', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
    ]
